--
-- create new database 'i2b2' with its users
--

CREATE DATABASE i2b2;

\connect i2b2

CREATE USER i2b2crcdata WITH PASSWORD 'demouser';
CREATE USER i2b2hive WITH PASSWORD 'demouser';
CREATE USER i2b2imdata WITH PASSWORD 'demouser';
CREATE USER i2b2metadata WITH PASSWORD 'demouser';
CREATE USER i2b2pm WITH PASSWORD 'demouser';
CREATE USER i2b2workdata WITH PASSWORD 'demouser';

CREATE SCHEMA AUTHORIZATION i2b2crcdata;
CREATE SCHEMA AUTHORIZATION i2b2hive;
CREATE SCHEMA AUTHORIZATION i2b2imdata;
CREATE SCHEMA AUTHORIZATION i2b2metadata;
CREATE SCHEMA AUTHORIZATION i2b2pm;
CREATE SCHEMA AUTHORIZATION i2b2workdata;
