#!/bin/sh
 
# Exit on error
set -e
 
# Source debconf library.
. /usr/share/debconf/confmodule
 
# Ask questions
db_input low aktin-notaufnahme/db_local || true
db_input low aktin-notaufnahme/db_host || true
db_input low aktin-notaufnahme/db_port || true
db_input low aktin-notaufnahme/db_user || true
db_input low aktin-notaufnahme/db_pass || true
 
# Show interface
db_go || true
