#!/bin/bash
set -e

. /usr/share/debconf/confmodule

case "$1" in
	remove)
		db_input high $DPKG_MAINTSCRIPT_PACKAGE/dis_apache2_proxy_http || true
		db_input high $DPKG_MAINTSCRIPT_PACKAGE/dis_apache2_php_curl || true
		db_go || true
		db_fset $DPKG_MAINTSCRIPT_PACKAGE/dis_apache2_proxy_http seen false
		db_fset $DPKG_MAINTSCRIPT_PACKAGE/dis_apache2_php_curl seen false

		db_get $DPKG_MAINTSCRIPT_PACKAGE/dis_apache2_proxy_http
		if [ "$RET" = "Yes" ]; then
			echo "Disabling apache2 proxy_http module ..."
			a2dismod proxy_http >/dev/null || true
		fi
		db_get $DPKG_MAINTSCRIPT_PACKAGE/dis_apache2_php_curl
		if [ "$RET" = "Yes" ]; then
			echo "Disabling apache2 php-curl extension ..."
			sed -i 's/extension=curl/;extension=curl/g' /etc/php/*/apache2/php.ini || true
		fi
		a2disconf aktin-j2ee-reverse-proxy >/dev/null 2>&1 || true
		systemctl restart apache2 || true

		rm -rf /opt/wildfly/standalone/{tmp,configuration,data,log}
		rm -f /opt/wildfly/standalone/deployments/*.{deployed,failed,isdeploying,pending}
		rm -f /opt/wildfly/standalone/deployments/{crc,im,ont,pm,work}-ds.xml
		;;
	purge)
		DWH_SHARED=$(echo $DPKG_MAINTSCRIPT_PACKAGE | awk -F '-' '{print $1"-"$2}')
		PSQL=""
		db_get $DWH_SHARED/db_conn
		if [ "$RET" = "unix" ]; then
			PSQL="sudo -u postgres psql"
			echo "Connecting to postgres via local unix socket."
		else
			db_get $DWH_SHARED/db_host
			host="$RET"
			db_get $DWH_SHARED/db_port
			port="$RET"
			db_get $DWH_SHARED/db_user
			user="$RET"
			db_get $DWH_SHARED/db_pass
			pass="$RET"
			PSQL="psql postgresql://$user:$pass@$host:$port?sslmode=require"
			echo "Connecting to postgres via TCP/IP to $host:$port."
		fi
		echo "Dropping I2B2 database ..."
		eval "$PSQL -v ON_ERROR_STOP=1" <<EOF >/dev/null
__I2B2_DROP__

EOF
		db_purge
		;;
esac

