#!/bin/bash
set -e

. /usr/share/debconf/confmodule
DEBCONF_NAME=$(echo $DPKG_MAINTSCRIPT_PACKAGE | awk -F '-' '{print $1"-"$2}')

# activate php-curl extension for apache2
if [[ -n $(grep ";extension=curl" /etc/php/*/apache2/php.ini) ]]; then
	echo -e "\e[1;33mPHP-curl für apache2 wird aktiviert.\e[0m"
	sed -i 's/;extension=curl/extension=curl/' /etc/php/*/apache2/php.ini
else
	echo -e "PHP-curl für apache2 wurde bereits aktiviert."
fi
a2enmod proxy_http || true
a2enconf aktin-j2ee-reverse-proxy || true
systemctl restart apache2

# count databases with name i2b2
PSQL=""
db_get $DEBCONF_NAME/db_conn
if [ "$RET" = "unix" ]; then
	PSQL="sudo -u postgres psql"
	echo "Connecting to postgres via local unix socket."
else
	db_get $DEBCONF_NAME/db_host
	host="$RET"
	db_get $DEBCONF_NAME/db_port
	port="$RET"
	db_get $DEBCONF_NAME/db_user
	user="$RET"
	db_get $DEBCONF_NAME/db_pass
	pass="$RET"
	PSQL="psql postgresql://$user:$pass@$host:$port?sslmode=require"
	echo "Connecting to postgres via TCP/IP to $host:$port."
fi

if  [[ $(eval "$PSQL -l" | grep "i2b2" | wc -l) == 0 ]]; then

	# create database i2b2 and respective users
	echo -e "Creating i2b2 database and users ..."
	eval "$PSQL -v ON_ERROR_STOP=1 -f /usr/share/$DPKG_MAINTSCRIPT_PACKAGE/database/i2b2_postgres_init.sql" > /dev/null

	# build i2b2 data and load into database
	echo -e "Seeding i2b2 database ..."
	eval "$PSQL -d i2b2 -f /usr/share/$DPKG_MAINTSCRIPT_PACKAGE/database/i2b2_db.sql" > /dev/null
else
	echo -e "i2b2 database already exists. Skipping ..."
fi

id -u wildfly >/dev/null || adduser --system --group --disabled-login --home /var/lib/wildfly wildfly
chown -R wildfly:wildfly /opt/wildfly /var/lib/aktin
systemctl daemon-reload
systemctl enable wildfly
systemctl start wildfly

